/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MathRouteImport } from './routes/math'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as CpRouteImport } from './routes/cp'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerIndexRouteImport } from './routes/career/index'
import { Route as CareerSavedRouteImport } from './routes/career/saved'
import { Route as CareerPortfolioRouteImport } from './routes/career/portfolio'
import { Route as CareerJobsRouteImport } from './routes/career/jobs'
import { Route as CareerCertificationsRouteImport } from './routes/career/certifications'
import { Route as CareerAchievementsRouteImport } from './routes/career/achievements'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const CpRoute = CpRouteImport.update({
  id: '/cp',
  path: '/cp',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerIndexRoute = CareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerRoute,
} as any)
const CareerSavedRoute = CareerSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => CareerRoute,
} as any)
const CareerPortfolioRoute = CareerPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => CareerRoute,
} as any)
const CareerJobsRoute = CareerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CareerRoute,
} as any)
const CareerCertificationsRoute = CareerCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => CareerRoute,
} as any)
const CareerAchievementsRoute = CareerAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => CareerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/career': typeof CareerRouteWithChildren
  '/cp': typeof CpRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/internships': typeof InternshipsRoute
  '/journal': typeof JournalRoute
  '/leaderboard': typeof LeaderboardRoute
  '/math': typeof MathRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/tasks': typeof TasksRoute
  '/career/achievements': typeof CareerAchievementsRoute
  '/career/certifications': typeof CareerCertificationsRoute
  '/career/jobs': typeof CareerJobsRoute
  '/career/portfolio': typeof CareerPortfolioRoute
  '/career/saved': typeof CareerSavedRoute
  '/career/': typeof CareerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/cp': typeof CpRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/internships': typeof InternshipsRoute
  '/journal': typeof JournalRoute
  '/leaderboard': typeof LeaderboardRoute
  '/math': typeof MathRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/tasks': typeof TasksRoute
  '/career/achievements': typeof CareerAchievementsRoute
  '/career/certifications': typeof CareerCertificationsRoute
  '/career/jobs': typeof CareerJobsRoute
  '/career/portfolio': typeof CareerPortfolioRoute
  '/career/saved': typeof CareerSavedRoute
  '/career': typeof CareerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/career': typeof CareerRouteWithChildren
  '/cp': typeof CpRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/internships': typeof InternshipsRoute
  '/journal': typeof JournalRoute
  '/leaderboard': typeof LeaderboardRoute
  '/math': typeof MathRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/tasks': typeof TasksRoute
  '/career/achievements': typeof CareerAchievementsRoute
  '/career/certifications': typeof CareerCertificationsRoute
  '/career/jobs': typeof CareerJobsRoute
  '/career/portfolio': typeof CareerPortfolioRoute
  '/career/saved': typeof CareerSavedRoute
  '/career/': typeof CareerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/ai'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/career'
    | '/cp'
    | '/goals'
    | '/habits'
    | '/internships'
    | '/journal'
    | '/leaderboard'
    | '/math'
    | '/notifications'
    | '/projects'
    | '/resume'
    | '/roadmap'
    | '/settings'
    | '/study'
    | '/tasks'
    | '/career/achievements'
    | '/career/certifications'
    | '/career/jobs'
    | '/career/portfolio'
    | '/career/saved'
    | '/career/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/ai'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/cp'
    | '/goals'
    | '/habits'
    | '/internships'
    | '/journal'
    | '/leaderboard'
    | '/math'
    | '/notifications'
    | '/projects'
    | '/resume'
    | '/roadmap'
    | '/settings'
    | '/study'
    | '/tasks'
    | '/career/achievements'
    | '/career/certifications'
    | '/career/jobs'
    | '/career/portfolio'
    | '/career/saved'
    | '/career'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/ai'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/career'
    | '/cp'
    | '/goals'
    | '/habits'
    | '/internships'
    | '/journal'
    | '/leaderboard'
    | '/math'
    | '/notifications'
    | '/projects'
    | '/resume'
    | '/roadmap'
    | '/settings'
    | '/study'
    | '/tasks'
    | '/career/achievements'
    | '/career/certifications'
    | '/career/jobs'
    | '/career/portfolio'
    | '/career/saved'
    | '/career/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  CareerRoute: typeof CareerRouteWithChildren
  CpRoute: typeof CpRoute
  GoalsRoute: typeof GoalsRoute
  HabitsRoute: typeof HabitsRoute
  InternshipsRoute: typeof InternshipsRoute
  JournalRoute: typeof JournalRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MathRoute: typeof MathRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  StudyRoute: typeof StudyRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cp': {
      id: '/cp'
      path: '/cp'
      fullPath: '/cp'
      preLoaderRoute: typeof CpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/': {
      id: '/career/'
      path: '/'
      fullPath: '/career/'
      preLoaderRoute: typeof CareerIndexRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/saved': {
      id: '/career/saved'
      path: '/saved'
      fullPath: '/career/saved'
      preLoaderRoute: typeof CareerSavedRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/portfolio': {
      id: '/career/portfolio'
      path: '/portfolio'
      fullPath: '/career/portfolio'
      preLoaderRoute: typeof CareerPortfolioRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/jobs': {
      id: '/career/jobs'
      path: '/jobs'
      fullPath: '/career/jobs'
      preLoaderRoute: typeof CareerJobsRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/certifications': {
      id: '/career/certifications'
      path: '/certifications'
      fullPath: '/career/certifications'
      preLoaderRoute: typeof CareerCertificationsRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/achievements': {
      id: '/career/achievements'
      path: '/achievements'
      fullPath: '/career/achievements'
      preLoaderRoute: typeof CareerAchievementsRouteImport
      parentRoute: typeof CareerRoute
    }
  }
}

interface CareerRouteChildren {
  CareerAchievementsRoute: typeof CareerAchievementsRoute
  CareerCertificationsRoute: typeof CareerCertificationsRoute
  CareerJobsRoute: typeof CareerJobsRoute
  CareerPortfolioRoute: typeof CareerPortfolioRoute
  CareerSavedRoute: typeof CareerSavedRoute
  CareerIndexRoute: typeof CareerIndexRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerAchievementsRoute: CareerAchievementsRoute,
  CareerCertificationsRoute: CareerCertificationsRoute,
  CareerJobsRoute: CareerJobsRoute,
  CareerPortfolioRoute: CareerPortfolioRoute,
  CareerSavedRoute: CareerSavedRoute,
  CareerIndexRoute: CareerIndexRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  CareerRoute: CareerRouteWithChildren,
  CpRoute: CpRoute,
  GoalsRoute: GoalsRoute,
  HabitsRoute: HabitsRoute,
  InternshipsRoute: InternshipsRoute,
  JournalRoute: JournalRoute,
  LeaderboardRoute: LeaderboardRoute,
  MathRoute: MathRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  StudyRoute: StudyRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
